### PR TITLE
Added type-forwarder for Unity.Compat to fix - https://groups.google.com/forum/#!topic/firebase-talk/2w1Lk62VIcg

### PR DESCRIPTION
**Pull request by bryanedds**
Added type-forwarder for Unity.Compat to fix - https://groups.google.com/forum/#!topic/firebase-talk/2w1Lk62VIcg

### CODE REVIEW

**Comment by montymxb** [comment]
Hi @bryanedds , thanks for the PR. I should note that our CI does _not_ account for Unity related builds as of this time. It's something we'll hopefully have in the future however. I'm a bit out of the loop regarding the issue you linked to, can you provide details here in regards to:
1. Existing issue this fixes (include details, os and unity version would be excellent)
2. How this fixes it
3. How to replicate the existing issue (we'll want to verify ourselves if we can)

In the future I think I'm going to add in a PR/issue template since this SDK tends to cover a _very_ broad range of OSs, frameworks, devices, envirionments and more. Having these details up front to know exactly what this pertains to will help us a lot with moving PRs & issues along 👍 .

**Comment by PathToLife** [comment]
Thanks for this! Will fix issues with .NET 4.5 and Google Firebase when trying to return Tuples
image

image

**Comment by stewartmiles** [comment]
FYI https://github.com/bryanedds/Parse-SDK-dotNET/pull/1 plumbs this into the Unity plugin build process.  @bryanedds any chance you could review / merge then rebase & squash this pull request for merging?

**Comment by TobiasPott** [comment]
Due to changes made to the repository and upcoming changes to provide support for non standard .NET platforms (Unity, Xamarin etc.) this pull request is outdated and will not be merged.
If any issues with Unity support in the future arise

**Pull request closed without merging**
