### PR TITLE
Update documentation around initialization of ParseClient

### PR DESCRIPTION
**Pull request by ryanmcdonough**
Fix documentation regarding initializing the ParseClient

### CODE REVIEW

**Comment by TobiasPott** [comment]
Hi @ryanmcdonough 
I've checked the pull request and your changes and appreciate your effort to add documentation to the code.
I've noticed that you've introduced a typo for the "ApplicationID" property. It's shows "ApplicationIx". Could you fix this and update/resubmit your pull request?

**Comment by ryanmcdonough** [comment]
Hey @TobiasPott thats sorted now.

**Comment by TobiasPott** [comment]
Thank you very much @ryanmcdonough , 
another thing you may elaborate so I can understand the change is the change of the "Key" property to "WindowsKey". As the actual name of the property did not change I think it might be confusing using a different name in the Readme.md compared to the sources.
Sorry for being picky on a PR for documentation, though.

**Comment by ryanmcdonough** [comment]
@TobiasPott - totally understand, so when I was using the package locally it's using WindowsKey however reviewing the code on github it's just Key - i'll revert my change on that

**Comment by TobiasPott** [comment]
@ryanmcdonough Thank you very much. =)
I assume I'll get notified when you update this pull request and I'll proceed with merging it then.

**Comment by ryanmcdonough** [comment]
All updated @TobiasPott :)

**Comment by TobiasPott** [comment]
Thank you very much @ryanmcdonough 
Your pull request have been merged into the master branch. 

I appreciate your contribution and your help. Feel free to continue to do so =).

**Pull request merged**
