### PR TITLE
resolved issue " Xamarin project error System.EntryPointNotFoundException: GetModuleFileName"

### PR DESCRIPTION
**Pull request by hirenvyas**
-  change GetEntryAssembly() to GetExecutingAssembly()

### CODE REVIEW

**Comment by TobiasPott** [comment]
Hi @hirenvyas could you elaborate on what this changes do and which problems it addresses?
Does it only apply to the Xamarin workflow or did you do any checks on .NET Standard or .NET Framework 4.x or even Unity?

**Comment by hirenvyas** [comment]
hello @TobiasPott : On Past When I used that Package I got error " Xamarin project error System.EntryPointNotFoundException: GetModuleFileName: on my Android project its work great for iOS , The issue behind is Assembly not getting entry point to load in Android platform.

**Comment by TobiasPott** [comment]
@Hiren-Vyas I see the problem and similar issues happen when using the GetEntryAssembly() inside Unity3D projects targeting mobile platforms.

Unfortunately this does not finally solve #300. Alex described his assumption about the cause being the calling assembly in case of Xamarin (I'll support this assumption).

If we took the GetExecutingAssembly() solution you suggest the parse caching and internal information (specific everything in VersionInformation struct) will use the information of the Parse.dll instead of the actual application running the Parse code. 
As far as I understand the current state and would expect it to be, the information should reflect the actual applications info (e.g. your xamarin app name and versioning).

To solve this issue in a broader way it is necessary to add additional configuration or build options to the Parse SDK assembly.
I'm doing it in a very rough way for our Unity3D applications and could imagine that some sort of platform configuration can be derived from it.

**Comment by TobiasPott** [comment]
Due to upcoming changes to the repository and the incompleteness of this pull request, the changes included will not be applied.
It should be possible to use the Parse SDK with Xamarin for platforms like Android and iOS alike.

If new problems arise in the future please create a new issue to discuss solutions or create a pull request to provide fixes.

**Pull request closed without merging**
