### PR TITLE
README overhaul top section

### PR DESCRIPTION
**Pull request by TomWFox**

### CODE REVIEW

**Comment by TobiasPott** [comment]
Hi @TomWFox 
I'm currently doing some maintenance on this repo and couldn't assess your PR.
This is just for clarifications on the Readme and you are still working on it (as it is still in draft state)?
Kind regards
Tobias

**Comment by TomWFox** [comment]
Hi @TobiasPott 👋 

Good to hear! This PR is still not finished, it is mainly getting it ready for our new open collective sponsorship tiers, I'll get to it soon.

**Comment by TobiasPott** [comment]
Hi @TomWFox 
thank you for the update on this. =)

**Comment by saamerm** [comment]
@TomWFox do we still need this?

**Pull request closed without merging**
