### PR TITLE
fix: `Parse.ParseUser.LogOutAsync` optimization

### LINKED ISSUE #400: Parse.ParseUser.LogOutAsync test fails
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-dotNET/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse .NET SDK](https://github.com/parse-community/Parse-SDK-dotNET/releases). 

### Issue Description

`Parse.ParseUser.LogOutAsync` test fails.

### Steps to reproduce

See https://github.com/parse-community/Parse-SDK-dotNET/actions/runs/12424201056/job/34688986371#step:8:867.

### PR DESCRIPTION
**Pull request by YBTopaz8**
Fixed an issue Parse LogoutAsync's test would not pass. 

Closes #400 

Now All user tests so far pass hopefully better coverage too.;
image

### CODE REVIEW

**Comment by YBTopaz8** [comment]
Curious to know the coverage now

**Comment by YBTopaz8** [comment]
@mtrezza this should be 2nd to be approved

**Review by mtrezza — COMMENTED** [review]
Could you just take a look at the warnings in the CI regarding unused vars, etc? There may be some clean-up needed.

**Comment by mtrezza** [comment]
I wonder why this PR contains so many changes while it is supposed to fix only 1 failing test. For example, what do the changes in `Parse.Tests/AnalyticsTests.cs` have to do with the user logout test?

**Comment by YBTopaz8** [comment]
Hi @mtrezza .

The reason for those is because I needed to cleanup tests which 
1. You requested I do
2. I mentioned in my last commit message
3. It's likely the first change we see when reviewing changes.
image
All of these were cleanups and re-adjustments (Except Object Tests which only has even more test I forgot to strip out).
like changing from async void to async task otherwise the test might not run at all or as expected.
```
    [TestMethod]
    ~public async void TestGetCurrentInstallation()~ THIS
    public async Task TestGetCurrentInstallation() - is now this
    {
```

the one file with changes that were not warranted was ObjectTest and that's because As I had done my overall fix over 2days ago, I had to ensure tests work and I even added more tests for coverage.
After being asked to separate, that must've been the only file I forgot to reamend after copying and pasting.

If you wish for me to remove all the code cleanups, I will, but that will lead to warnings and errors that I would frankly not circle back to as these will be redundant.

If you wish for me to remove the additional tests codes from ObjectTest so as to stick to the scope... sure. I'll do that.
Just tell so and I'll delete the additional lines and push.

As of now, I am happy and they all pass and any specific change is either a cleanup or a code TEST addition. 
Should You wish for me to change anything, I will. Should an issue arise after a change , I'll investigate and if the reason is due to the change I made on your requests, I'll inform you at least and leave them as such. 

Thank you.

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
Was there an actual bug in the code or was this merely a test issue?

**Comment by YBTopaz8** [comment]
Only tests
It's the Tests test were an issue since I wasn't good at those one - until now

**Comment by YBTopaz8** [comment]
ParseUser.cs
Changed
```
```

**Comment by YBTopaz8** [comment]
- ParseUser.cs
Changed `get => ContainsKey("authData") ? AuthData["authData"] as IDictionary<string, IDictionary<string, object>> : null;`
to
```
get
        {
            if (ContainsKey("authData"))
            {
                return this["authData"] as IDictionary<string, IDictionary<string, object>>;
            }
            else
                return null;
        }
```
It's literally the same thing, just expanded them. for readibility.
- Parse/Infrastructure/Execution/UniversalWebClient.cs

```
Stream data = httpRequest.Data;
        if (data != null || httpRequest.Method.Equals("POST", StringComparison.OrdinalIgnoreCase))
{
            message.Content = new StreamContent(data ?? new MemoryStream(new byte[0]));
}
```
to ensure that Data is *Always* passed in http request as sometimes it would be null
```
if ((httpRequest.Data is null && httpRequest.Method.ToLower().Equals("post")
             ? new MemoryStream(new byte[0])
             : httpRequest.Data) is Stream { } data)
{
            message.Content = new StreamContent(data);

}
```

Other changes are just done due to copy pasting since I had to split them

**Comment by YBTopaz8** [comment]
Explained [here.](https://github.com/parse-community/Parse-SDK-dotNET/pull/404#issuecomment-2559379383)

**Comment by mtrezza** [comment]
> to ensure that Data is Always passed in http request as sometimes it would be null

That sounds like a separate issue, more than a refactor. I'm having doubts; how much work would it be to strip this PR down to the bare issue of Parse User login?

**Comment by YBTopaz8** [comment]
Reverted those changed.
I do not believe we need to open a PR for variable assignment placement.
image

**Comment by mtrezza** [comment]
Maybe there's a misunderstanding. The refactors are not the issue, I said earlier that we can just merge them.

But you mentioned earlier that the changes in `UniversalWebClient.cs` ...

> ensure that Data is Always passed in http request as sometimes it would be null

How is that related to the logout issue? It sounds like a separate issue?

I also see some code being removed like timeouts:

> using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(30)); // Timeout after 30 seconds
> ...
> Timeout = TimeSpan.FromSeconds(15) // Ensure timeout is respected.

How are these changes related to the logout issue?

**Comment by YBTopaz8** [comment]
Sure.
Let me preface by giving you the context through which I was in when doing the PR.
I when I did PR one that was merged, It was a core system update for it to be using new approaches rather than legacy here and there.
That over all update brought issues linked to my lack of proper testing skills at the time but all the tests remaining at that time (189 instead of 200 initially) passed so 11 tests were missing (- out of my notice) but we both realized some tests didn't pass, notably Logout and Test Link.

The core issue for logout rested on the UniversalClient.cs file because the NEW approach, at the time, wasn't accounting for when the logout URL doesn't exist anymore (Like Facebook auth) as well as moment when Parse gave an error.

And that needed some time because the server replies back, so I added a slightly higher timeout - NOT necessary but useful to give enough time for a round trip even if (and especially) when rejected.
Thing is, That was code was removed afterwards. because they were MY workaround. 
In #404, I removed it since the code structure was now much more understandable to me, so I didn't need to rely much on this timeout approach.
Hence why I changed some various assignment positions because when testing I was to ensure DataTransfer goes first. (Parse Relations didn't get transferred before)

Like I said as we had v4.0.0 merged, I immediately went back to at least increase test coverage or fix immediate bugs since I had feedback on my end too, given that my update had broken Parse LQ.

So It felt all the more natural to push a full corrective update with all fixes AND more coverages, which was my aim ultimately - given that I had just learned and understood, I wanted to give back.

But these separation led to more questions that answer.
1. All of your questions stem from the fact that I copy/pasted my solutions from the main branch where I fixed to a 2nd branch just for logout.
2. All of your question where I answer "it is just a placement change" are pretty much just.. that. Nothing deeper and if that doesn't suit., sure I'll revert those changes.

My aim with the first PR was to quickly push a more stable and overall reliable code. Hence why I was curious about the code coverage in the beginning. But with all these tests failing online and passing on my end, then back and forths I'm just hoping  it fixes the issues people face using the official update.
(I pushed my updated 3 days ago and so far so good)

**Comment by YBTopaz8** [comment]
I'll hereby explain to you WHAT each change mean. I preface by saying too ; this is not a test on your knowledge or so.
I understand we are busy and would prefer to have things clear all at once.
So, I'll explain;
- ParseUser: 106 & 114: removed debug lines, only good for Parse SDK dev
175: spaced out the line into multiple for readability

- UWC : I simplified the code as the previous one was a workaround to do the logout. If you look through, I had an if-else on 82 that did the same http actions but logout was done slightly differently since at the time I needed more to be considered, so I had splitted first (as seen in v4.0.0). then recombined after fixing, as seen in this PR

I'll

**Comment by mtrezza** [comment]
> I had an if-else on 82 that did the same http actions but logout was done slightly differently since at the time I needed more to be considered

Makes more sense to me now, I think we can go ahead now. Thanks for taking the take to lay it all out.

**Review by mtrezza — APPROVED** [review]
Looks good

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1](https://github.com/parse-community/Parse-SDK-dotNET/releases/tag/4.0.1)

**Pull request merged**
