### PR TITLE
feat: Missing Methods and Implementations after v4.0. 

### LINKED ISSUE #397: Missing methods in Parse .NET SDK 4.0
### Issue when upgrading to Parse SDK 4.0

After upgrading to Parse SDK 4.0, I've run into a few issues due to changes in the API. Here’s what I’ve encountered:

1. **`user.Username` is no longer accessible**
   - In previous versions, I was able to access the `Username` field directly with `user.Username`, but in version 4.0, that field seems to be missing. The following code no longer works:
     ```csharp
     var user = ParseClient.Instance.GetCurrentUser();
     if (user.Username == "Test123")
     {
         // logic
     }
     ```

2. **`user.GetRelation<ParseObject>("SomeClass")` is no longer available**
   - The method `GetRelation<ParseObject>("SomeClass")` no longer works. I'm unsure how to handle relations in version 4.0 since it seems like this method was changed or removed. Here’s the code that no longer functions:
     ```csharp
     var someClassRelation = user.GetRelation<ParseObject>("SomeClass");
     ```

3. **`await user.SaveAsync()` is no longer working**
   - The method `SaveAsync()` is no longer available on `ParseUser` objects directly. The following code no longer works:
     ```csharp
     await user.SaveAsync();
     ```

---

### Environment

- **Parse SDK Version**: 4.0
- **Platform**: .NET 9.0 MAUI, iOS/Android (or specify your platform)

---

Any guidance or clarification on these issues would be greatly appreciated! Thanks in advance.  Maybe @YBTopaz8 can help?  Thanks!

### LINKED ISSUE #400: Parse.ParseUser.LogOutAsync test fails
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-dotNET/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse .NET SDK](https://github.com/parse-community/Parse-SDK-dotNET/releases). 

### Issue Description

`Parse.ParseUser.LogOutAsync` test fails.

### Steps to reproduce

See https://github.com/parse-community/Parse-SDK-dotNET/actions/runs/12424201056/job/34688986371#step:8:867.

### PR DESCRIPTION
**Pull request by YBTopaz8**
- Fixed a logout issue where logging out WILL logout but the test failed.
- Fixed issues where Parse Relations/Pointers never worked after v4.0 (incomplete decoding)
- Added about 70+ tests to help improve code coverage at least in the very critical parts.

- closes #397 
- closes #400  too

Redid this PR and fixed conflicts
Code should be more reliable now 👍🏾

### CODE REVIEW

**Comment by YBTopaz8** [comment]
Here I would either have to add .net7, 8 and 9 in parse and test or you would remove them from checks.
(we had the conversation before and concluded with me going with .net 6 only as seen in v4 release)

**Comment by mtrezza** [comment]
Amazing work! Could you please split this PR into individual PRs that are scoped to a single issue? Essentially a PR for each of the points that you outlined in https://github.com/parse-community/Parse-SDK-dotNET/pull/402#issue-2754219661. Please see [here](https://github.com/parse-community/parse-server/blob/alpha/CONTRIBUTING.md#scope) why.

**Comment by YBTopaz8** [comment]
Still passing
image

**Comment by mtrezza** [comment]
@YBTopaz8 Is there any test coverage that could be re-used in a new PR dedicated to only increase coverage?

**Comment by YBTopaz8** [comment]
Not really, no. Most of the tests here were (slightly modified) and added

**Pull request closed without merging**
