### PR TITLE
Updated project info for nuget package release

### PR DESCRIPTION
**Pull request by TobiasPott**
This pull request includes updates to the nuget package info and assembly information in preparation of nuget package upload and upload of release binaries for this repository on github itself.

### CODE REVIEW

**Comment by TheFanatr** [comment]
I saw you bumped the version to v2; the version was 2.0.0-develop-0001 in case there would need to be fixes and renames or some other breaking changes, and so that we can add LiveQuery support for this release. I’d at least release “develop” prereleases on NuGet until we’re sure the current 2.0 is final. Up to you.

**Comment by TobiasPott** [comment]
Yeah, I actually didn't get to a specific opinion on that. It makes sense as you say to include some sort of hint about the development being in progress on this release.

I'll update nuget and the release section in here with an updated information.
I would revert back to your schema 2.0.0-develop-1 but would drop the zero padding on the last counter.

I was a bit impatient on this one to be honest -.-

**Comment by TheFanatr** [comment]
I need the padding because NuGet versioning doesn’t dictates that 9 > 10 and 10 = 100, etc.

**Comment by TobiasPott** [comment]
Oh what? That sounds kind of stupid to trim the trailing ones -.-
But well that is a good reason to do it your way. 
Would have been nice if the docs for uploading a nuget package included such information, as I just looked it up yesterday to be sure what steps to perform -.-.

I have a slightly off-topic question: @TheFanatr would you mind/like to join the parse team as a member? @TomWFox should be able to add you to the team. I think it would be great to have a few more people (more than tom and me) handling the repository and discuss topics and general things about future development steps to improve the SDK.

**Comment by TheFanatr** [comment]
> I have a slightly off-topic question: @TheFanatr would you mind/like to join the parse team as a member?

Sure. I won’t be available to help all the time but will be able to do some stuff and answer technical questions, et cetera.

**Comment by TomWFox** [comment]
Happy to do that, it involves a vote on the forum - I'm on a roll with them at the moment as we've got a couple other people to add to the org!

**Comment by TobiasPott** [comment]
> Happy to do that, it involves a vote on the forum - I'm on a roll with them at the moment as we've got a couple other people to add to the org!

Is there anything I can assist with? 
Will you create the forum vote proposal?
Oh and what are PMC members you mentioned in the other vote proposal?

**Comment by TomWFox** [comment]
No, it's all good - I've drafted it and I'll post later.

The PMC members are essentially the core contributors you can see them on the [team doc](https://github.com/parse-community/Governance/blob/master/TEAM.md#project-management-committee-pmc).

**Comment by TomWFox** [comment]
The vote is live now - [here](https://community.parseplatform.org/t/vote-to-add-alex-fanat-thefanatr-as-a-committer/479/2)

**Pull request merged**
